### ISSUE TITLE
Jul18 manual release tests: debian9 (@alba)

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#785]
This issue is created for reporting the results of the manual tests for Jul18 release on **debian-stretch** (this is done in ALBA in parallel to those by @teresanunez  in #783).

They are also considered for the release PR: #784 

### Installation
- [x] Install Taurus from the tar.gz : `pip install https://ci.appveyor.com/api/buildjobs/q6g52a22q2nkurst/artifacts/dist%2Ftaurus-4.4.0a0.tar.gz` 

### Taurusdemo

- [x] Test all of the buttons of the taurusdemo. All demos should launch correctly and without raising exceptions
- [x] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, the formatter, etc.
- [x] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#rvalue.magnitude`, `eval:Q('1mm')#rvalue.unit"`, `eval:10*arange(9)#rvalue[3:4]`)
- [x] For LCD: Test the foreground roles and the background role
- [x] For Led: Test the colors, ON color, Off color.

### taurusplot
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Execute: `taurusplot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [x] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [x] Check mouse wheel Zoom
- [x] Test panning (dragging with CTRL pressed)
- [x] Test inspector mode
- [x] Test pause mode
- [x] Move curves between axes by clicking on legend (and test zoom on Y2)
- [x] Test plot configuration dialog
- [x] Test changing curve titles
- [x] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [x] Open the "Input data selection" dialog and add/remove/reorder /edit models
- [x] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurustrend
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Execute: `taurustrend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [x] Execute: `taurustrend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [x] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [x] Check mouse wheel Zoom
- [x] Test panning (dragging with CTRL pressed)
- [x] Test inspector mode
- [x] Test pause mode
- [x] Move curves between axes by clicking on legend (and test zoom on Y2)
- [x] Test plot configuration dialog
- [x] Test Forced reading mode
- [x] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [x] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### Test taurusimage

- [x] Execute `taurusimage --demo`
- [x] try to resize the image and move it using the mouse.

### taurustrend2d

- [x] Execute: `taurustrend2d --demo --taurus-polling-period 333`
- [ ] **FAIL** Execute: `taurustrend2d -xt --demo --taurus-polling-period 333`  **(known to fail in 4.1.0)**
- [x] Execute: `taurustrend2d -xe --demo --taurus-polling-period 333`
- [x] Test auto-scroll and auto-scale tools
- [ ] **DID NOT TEST** Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored **-- you may need a taurusgui or dong it programmatically--**)

### Tauruscurve & taurustrend1d
(unused and to be deprecated, you may test but **do not worry too much if they fail**)
- [ ] Execute: `tauruscurve --demo` **IT FAILS TO LAUNCH: `TypeError: native Qt signal is not callable`. SKIPPING THE REST OF THE TESTS FOR THESE 2 WIDGETS**
 
- [ ] Change size
- [ ] Move curve with mouse
- [ ] Resize curve with mouse
- [ ] Test some option of the menu with mouse.
- [ ] Execute: `taurustrend1d "eval:Q(rand(),'mm')"` and test it in the same way

### taurusdesigner
- [x] Check that taurusdesigner is correctly opened and taurus widgets are present in the catalog
- [x] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

### taurusdevicepanel
- [x] Execute: `taurusdevicepanel sys/tg_test/1`
- [x] Check that it opens correctly and that the attrs and commands are populated
- [x] Execute SwitchStates command (see that the state label changes to FAULT and its color to red)
      and then execute the Init command and the label returns to RUNNING (blue)

### tauruspanel
- [x] Execute: `tauruspanel`
- [x] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)

**NOTE: It is no longer possible to access the Change Tango Host action here. It should be re-added to tauruspanel GUI** 

### taurusform
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Launch `taurusform sys/tg_test/1/short_scalar`
- [x] go to label context menu, change the configuration and set range to (-1000, 1000), alarm to (-500, 500) and unit to `mm`. Close the form and relaunch. The new units should be used. Change the the write value and check that the orange color is used when in warning values, and that the write widget does not allow to write values out of range.
- [x] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96)
- [x] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [x] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [x] Test compact mode for all values (from the context menu of the whole form)
- [x] Test changing labels   **FAILED FOR DEVICES. THE PROBLEM ALSO EXISTS IN PREVIOUS RELEASES. I CREATED #786** 
- [x] Test changing the formatter for a single value (from the context menu of a value label) (use, e.g. `>>{}<<`)  **FAILED FOR ITEMS IN COMPACT MODE. I CREATED #787**
- [x] Test changing the formatter for all values (from the context menu of the whole form)
- [x] Test re-order of values with "Modify contents"
- [x] Test the different "show" buttons (tables, images, spectra)
- [x] Change the write widget of double_scalar by a TaurusWheelEdit  **WORKS WELL , but See #788**
- [x] Change other read and write widgets
- [x] ... other features from [user's guide](http://taurus-scada.org/users/ui/index.html)

### taurusgui
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Launch `taurusgui example01`
- [x] Test (un)lock view
- [x] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [x] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [x] Test saving and restoring perspectives
- [x] Test drag&drop from a form to a trend
- [x] Test clicking on "example01 synoptic" elements and check that the panels raised
- [x] Test that selecting a panel changes the selection on "example01 synoptic"
- [x] Test the actions in the menus
- [x] Create a new TaurusGui (call it `foogui`) with `taurusgui --new-gui` (follow the wizard)
- [x] Install `foogui` with pip (using a virtualenv may be a good idea)
- [x] launch `foogui` using the script that has been installed
- [x] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurusconfigbrowser
- [x] Open an ini file with taurusconfigbrowser and check that it is loaded correctly.

### taurusiconcatalog
- [x] Launch `taurusiconcatalog`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/en/latest/devel/icon_guide.html#taurus-icon-catalog)
- [x] Check that tooltips give info on each icon
- [x] Click on some icons and check that they give a bigger view of the icon and more info.

**Comment by cpascual** [comment]
while testing the container widgets with taurusdemo I got some deprecation warnings due to usage of useParentModel.

I hotfixed it in the release branch with  commit 25729f5

**Comment by cpascual** [comment]
All tests passed without problems. No regressions found. Only a couple of minor issues that I reported as new issues.

IMHO, the tests for debian9 are ok
